package render

import (
	"fmt"
	"os"
	"path/filepath"

	yamlv3 "gopkg.in/yaml.v3"

	"github.com/willswire/keel/internal/model"
	"github.com/willswire/keel/internal/zarf"
)

type ComposeOptions struct {
	App  model.ComposeAppSpec
	Dist model.DistSpec
}

type composeComponentSpec struct {
	Name          string
	Namespace     string
	ManifestFiles []string
	Image         string
	ImageArchive  string
	UsesArchive   bool
}

func GenerateCompose(opts ComposeOptions) error {
	if err := os.MkdirAll(opts.Dist.ManifestDir, 0o755); err != nil {
		return fmt.Errorf("create manifest directory: %w", err)
	}
	if err := os.MkdirAll(opts.Dist.ImageDir, 0o755); err != nil {
		return fmt.Errorf("create image directory: %w", err)
	}

	if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, "namespace.yaml"), namespaceTemplate, map[string]any{
		"Namespace": opts.App.Namespace,
	}); err != nil {
		return err
	}

	components := make([]composeComponentSpec, 0, len(opts.App.Services))

	for _, svc := range opts.App.Services {
		ports := buildTemplatePorts(svc.Dockerfile.ExposedPorts)
		runAsNonRoot, hasRunAsUser, runAsUser := userSecurity(svc.Dockerfile.User)

		deploymentRel := filepath.ToSlash(filepath.Join("manifests", fmt.Sprintf("deployment-%s.yaml", svc.Name)))
		if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, fmt.Sprintf("deployment-%s.yaml", svc.Name)), deploymentTemplate, map[string]any{
			"Name":         svc.Name,
			"Namespace":    svc.Namespace,
			"Image":        svc.Image,
			"Ports":        ports,
			"Env":          svc.Dockerfile.Env,
			"Command":      parseDockerArgs(svc.Dockerfile.Entrypoint),
			"Args":         parseDockerArgs(svc.Dockerfile.Cmd),
			"Healthcheck":  parseHealthcheck(svc.Dockerfile.Healthcheck),
			"RunAsNonRoot": runAsNonRoot,
			"HasRunAsUser": hasRunAsUser,
			"RunAsUser":    runAsUser,
		}); err != nil {
			return err
		}

		component := composeComponentSpec{
			Name:      svc.Name,
			Namespace: svc.Namespace,
			ManifestFiles: []string{
				"manifests/namespace.yaml",
				deploymentRel,
			},
			Image: svc.Image,
		}

		if len(ports) > 0 {
			serviceRel := filepath.ToSlash(filepath.Join("manifests", fmt.Sprintf("service-%s.yaml", svc.Name)))
			if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, fmt.Sprintf("service-%s.yaml", svc.Name)), serviceTemplate, map[string]any{
				"Name":      svc.Name,
				"Namespace": svc.Namespace,
				"Ports":     ports,
			}); err != nil {
				return err
			}
			component.ManifestFiles = append(component.ManifestFiles, serviceRel)

			primary, err := svc.PrimaryPort()
			if err != nil {
				return err
			}
			udsPackageRel := filepath.ToSlash(filepath.Join("manifests", fmt.Sprintf("uds-package-%s.yaml", svc.Name)))
			if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, fmt.Sprintf("uds-package-%s.yaml", svc.Name)), composeUDSPackageTemplate, map[string]any{
				"Name":        svc.Name,
				"Namespace":   svc.Namespace,
				"Host":        svc.Name,
				"PrimaryPort": primary.Number,
			}); err != nil {
				return err
			}
			component.ManifestFiles = append(component.ManifestFiles, udsPackageRel)
		}

		if svc.Build != nil {
			component.UsesArchive = true
			component.ImageArchive = filepath.ToSlash(filepath.Join("images", fmt.Sprintf("%s.tar", svc.Name)))
		}
		components = append(components, component)
	}

	return writeComposeZarfConfig(opts, components)
}

func writeComposeZarfConfig(opts ComposeOptions, components []composeComponentSpec) error {
	pkg := struct {
		APIVersion string `yaml:"apiVersion"`
		Kind       string `yaml:"kind"`
		Metadata   struct {
			Name        string `yaml:"name"`
			Version     string `yaml:"version"`
			Description string `yaml:"description,omitempty"`
		} `yaml:"metadata"`
		Components []struct {
			Name      string `yaml:"name"`
			Required  bool   `yaml:"required"`
			Manifests []struct {
				Name      string   `yaml:"name"`
				Namespace string   `yaml:"namespace,omitempty"`
				Files     []string `yaml:"files"`
			} `yaml:"manifests"`
			Images        []string `yaml:"images,omitempty"`
			ImageArchives []struct {
				Path   string   `yaml:"path"`
				Images []string `yaml:"images"`
			} `yaml:"imageArchives,omitempty"`
		} `yaml:"components"`
	}{}

	pkg.APIVersion = "zarf.dev/v1alpha1"
	pkg.Kind = "ZarfPackageConfig"
	pkg.Metadata.Name = opts.App.Name
	pkg.Metadata.Version = opts.App.Version
	pkg.Metadata.Description = fmt.Sprintf("Generated by keel from %s", opts.App.ComposeFilePath)

	for _, svc := range components {
		component := struct {
			Name      string `yaml:"name"`
			Required  bool   `yaml:"required"`
			Manifests []struct {
				Name      string   `yaml:"name"`
				Namespace string   `yaml:"namespace,omitempty"`
				Files     []string `yaml:"files"`
			} `yaml:"manifests"`
			Images        []string `yaml:"images,omitempty"`
			ImageArchives []struct {
				Path   string   `yaml:"path"`
				Images []string `yaml:"images"`
			} `yaml:"imageArchives,omitempty"`
		}{
			Name:     svc.Name,
			Required: true,
		}
		component.Manifests = append(component.Manifests, struct {
			Name      string   `yaml:"name"`
			Namespace string   `yaml:"namespace,omitempty"`
			Files     []string `yaml:"files"`
		}{
			Name:      svc.Name + "-manifests",
			Namespace: svc.Namespace,
			Files:     svc.ManifestFiles,
		})
		if svc.UsesArchive {
			component.ImageArchives = append(component.ImageArchives, struct {
				Path   string   `yaml:"path"`
				Images []string `yaml:"images"`
			}{
				Path:   svc.ImageArchive,
				Images: []string{svc.Image},
			})
		} else {
			component.Images = append(component.Images, svc.Image)
		}
		pkg.Components = append(pkg.Components, component)
	}

	yamlData, err := yamlv3.Marshal(pkg)
	if err != nil {
		return fmt.Errorf("marshal zarf config: %w", err)
	}
	preface := "# yaml-language-server: $schema=" + zarf.SchemaURL + "\n"
	return os.WriteFile(filepath.Join(opts.Dist.RootPath, "zarf.yaml"), append([]byte(preface), yamlData...), 0o644)
}

const composeUDSPackageTemplate = `apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  network:
    serviceMesh:
      mode: ambient
    expose:
      - service: {{ .Name }}
        selector:
          app.kubernetes.io/name: {{ .Name }}
        gateway: tenant
        host: {{ .Host }}
        port: {{ .PrimaryPort }}
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
`
