package render

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/zarf-dev/zarf/src/api/v1alpha1"
	sigsyaml "sigs.k8s.io/yaml"

	"github.com/willswire/keel/internal/model"
	"github.com/willswire/keel/internal/zarf"
)

type Options struct {
	App            model.AppSpec
	Dist           model.DistSpec
	ZarfMinVersion string
}

func Generate(opts Options) error {
	if err := os.MkdirAll(opts.Dist.ManifestDir, 0o755); err != nil {
		return fmt.Errorf("create manifest directory: %w", err)
	}
	if err := os.MkdirAll(opts.Dist.ImageDir, 0o755); err != nil {
		return fmt.Errorf("create image directory: %w", err)
	}

	ports := buildTemplatePorts(opts.App.Container.ExposedPorts)
	runAsNonRoot, hasRunAsUser, runAsUser := userSecurity(opts.App.Container.User)

	if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, "namespace.yaml"), namespaceTemplate, map[string]any{
		"Namespace": opts.App.Namespace,
	}); err != nil {
		return err
	}

	if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, "deployment.yaml"), deploymentTemplate, map[string]any{
		"Name":           opts.App.Name,
		"Namespace":      opts.App.Namespace,
		"Image":          opts.App.Image,
		"Ports":          ports,
		"Env":            opts.App.Container.Env,
		"Command":        parseContainerArgs(opts.App.Container.Entrypoint),
		"Args":           parseContainerArgs(opts.App.Container.Cmd),
		"Healthcheck":    parseHealthcheck(opts.App.Container.Healthcheck),
		"RunAsNonRoot":   runAsNonRoot,
		"HasRunAsUser":   hasRunAsUser,
		"RunAsUser":      runAsUser,
		"InitContainers": []renderedInitContainer{},
		"VolumeMounts":   []renderedVolumeMount{},
		"Volumes":        []renderedVolume{},
		"Resources":      renderedResources{},
	}); err != nil {
		return err
	}

	if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, "service.yaml"), serviceTemplate, map[string]any{
		"Name":      opts.App.Name,
		"Namespace": opts.App.Namespace,
		"Ports":     ports,
	}); err != nil {
		return err
	}

	primary, err := opts.App.PrimaryPort()
	if err != nil {
		return err
	}
	if err := writeTemplate(filepath.Join(opts.Dist.ManifestDir, "uds-package.yaml"), udsPackageTemplate, map[string]any{
		"Name":        opts.App.Name,
		"Host":        opts.App.Name,
		"PrimaryPort": primary.Number,
	}); err != nil {
		return err
	}

	if err := writeZarfConfig(opts); err != nil {
		return err
	}

	return nil
}

func writeZarfConfig(opts Options) error {
	pkg := v1alpha1.ZarfPackage{
		APIVersion: v1alpha1.APIVersion,
		Kind:       v1alpha1.ZarfPackageConfig,
		Metadata: v1alpha1.ZarfMetadata{
			Name:        opts.App.Name,
			Version:     opts.App.Version,
			Description: fmt.Sprintf("Generated by keel from %s", opts.App.ContainerfilePath),
		},
		Components: []v1alpha1.ZarfComponent{
			{
				Name:     opts.App.Name,
				Required: boolPtr(true),
				Manifests: []v1alpha1.ZarfManifest{
					{
						Name:      opts.App.Name + "-manifests",
						Namespace: opts.App.Namespace,
						Files: []string{
							"manifests/namespace.yaml",
							"manifests/deployment.yaml",
							"manifests/service.yaml",
							"manifests/uds-package.yaml",
						},
					},
				},
				ImageArchives: []v1alpha1.ImageArchive{
					{
						Path:   opts.Dist.ImageArchiveRel,
						Images: []string{opts.App.Image},
					},
				},
			},
		},
	}

	yamlData, err := sigsyaml.Marshal(pkg)
	if err != nil {
		return fmt.Errorf("marshal zarf config: %w", err)
	}
	preface := "# yaml-language-server: $schema=" + zarf.SchemaURL + "\n"
	return os.WriteFile(filepath.Join(opts.Dist.RootPath, "zarf.yaml"), append([]byte(preface), yamlData...), 0o644)
}

func boolPtr(v bool) *bool {
	return &v
}

func writeTemplate(path string, raw string, data map[string]any) error {
	tmpl, err := template.New(filepath.Base(path)).Funcs(template.FuncMap{
		"quote": strconv.Quote,
	}).Parse(raw)
	if err != nil {
		return fmt.Errorf("parse template for %s: %w", path, err)
	}
	buf := bytes.Buffer{}
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render template for %s: %w", path, err)
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

type renderedPort struct {
	Name     string
	Number   int
	Protocol string
}

type renderedInitContainer struct {
	Name    string
	Image   string
	Command []string
}

type renderedVolumeMount struct {
	Name      string
	MountPath string
	ReadOnly  bool
	SubPath   string
}

type renderedVolume struct {
	Name                  string
	PersistentVolumeClaim string
	SecretName            string
	ConfigMapName         string
}

type renderedResources struct {
	HasAny        bool
	HasLimits     bool
	LimitCPU      string
	LimitMemory   string
	HasRequests   bool
	RequestCPU    string
	RequestMemory string
}

func buildTemplatePorts(ports []model.Port) []renderedPort {
	out := make([]renderedPort, 0, len(ports))
	for i, p := range ports {
		name := fmt.Sprintf("port-%d-%s", p.Number, strings.ToLower(p.Protocol))
		if i == 0 && strings.EqualFold(p.Protocol, "TCP") {
			name = "http"
		}
		out = append(out, renderedPort{Name: name, Number: p.Number, Protocol: strings.ToUpper(p.Protocol)})
	}
	return out
}

func userSecurity(user string) (runAsNonRoot bool, hasRunAsUser bool, runAsUser int64) {
	trimmed := strings.TrimSpace(user)
	if trimmed == "" {
		return false, false, 0
	}
	base := trimmed
	if strings.Contains(base, ":") {
		base = strings.SplitN(base, ":", 2)[0]
	}
	if strings.EqualFold(base, "root") {
		return false, false, 0
	}
	if uid, err := strconv.ParseInt(base, 10, 64); err == nil {
		return uid != 0, true, uid
	}
	return true, false, 0
}

func parseContainerArgs(raw string) []string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return nil
	}
	if strings.HasPrefix(trimmed, "[") {
		var args []string
		if err := json.Unmarshal([]byte(trimmed), &args); err == nil {
			return args
		}
	}
	return strings.Fields(trimmed)
}

func parseHealthcheck(raw string) []string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return nil
	}
	tokens := strings.Fields(trimmed)
	if len(tokens) == 0 {
		return nil
	}
	modeIdx := 0
	for modeIdx < len(tokens) && strings.HasPrefix(tokens[modeIdx], "--") {
		modeIdx++
	}
	if modeIdx >= len(tokens) {
		return nil
	}
	mode := tokens[modeIdx]
	payload := strings.TrimSpace(strings.Join(tokens[modeIdx+1:], " "))
	if strings.EqualFold(mode, "NONE") {
		return nil
	}
	if strings.EqualFold(mode, "CMD-SHELL") {
		if payload == "" {
			return nil
		}
		return []string{"/bin/sh", "-c", payload}
	}
	if !strings.EqualFold(mode, "CMD") {
		return nil
	}
	if payload == "" {
		return nil
	}
	if strings.HasPrefix(payload, "[") {
		var args []string
		if err := json.Unmarshal([]byte(payload), &args); err == nil {
			return args
		}
	}
	return []string{"/bin/sh", "-c", payload}
}

const deploymentTemplate = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Name }}
    spec:
      securityContext:
        runAsNonRoot: {{ .RunAsNonRoot }}{{ if .HasRunAsUser }}
        runAsUser: {{ .RunAsUser }}{{ end }}{{ if .InitContainers }}
      initContainers:{{ range .InitContainers }}
        - name: {{ .Name }}
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          command:{{ range .Command }}
            - {{ quote . }}{{ end }}{{ end }}{{ end }}
      containers:
        - name: {{ .Name }}
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
{{- if .Resources.HasAny }}
          resources:{{ if .Resources.HasLimits }}
            limits:{{ if .Resources.LimitCPU }}
              cpu: {{ quote .Resources.LimitCPU }}{{ end }}{{ if .Resources.LimitMemory }}
              memory: {{ quote .Resources.LimitMemory }}{{ end }}{{ end }}{{ if .Resources.HasRequests }}
            requests:{{ if .Resources.RequestCPU }}
              cpu: {{ quote .Resources.RequestCPU }}{{ end }}{{ if .Resources.RequestMemory }}
              memory: {{ quote .Resources.RequestMemory }}{{ end }}{{ end }}
{{- end }}
{{- if .Command }}
          command:{{ range .Command }}
            - {{ quote . }}{{ end }}
{{- end }}
{{- if .Args }}
          args:{{ range .Args }}
            - {{ quote . }}{{ end }}
{{- end }}
{{- if .Ports }}
          ports:{{ range .Ports }}
            - name: {{ .Name }}
              containerPort: {{ .Number }}
              protocol: {{ .Protocol }}{{ end }}
{{- end }}{{ if .Env }}
          env:{{ range .Env }}
            - name: {{ .Name }}
              value: {{ quote .Value }}{{ end }}{{ end }}{{ if .VolumeMounts }}
          volumeMounts:{{ range .VolumeMounts }}
            - name: {{ .Name }}
              mountPath: {{ quote .MountPath }}{{ if .ReadOnly }}
              readOnly: true{{ end }}{{ if .SubPath }}
              subPath: {{ quote .SubPath }}{{ end }}{{ end }}
{{- end }}{{ if .Healthcheck }}
          livenessProbe:
            exec:
              command:{{ range .Healthcheck }}
                - {{ quote . }}{{ end }}
            initialDelaySeconds: 5
            periodSeconds: 30
{{- end }}
{{- if .Volumes }}
      volumes:{{ range .Volumes }}
        - name: {{ .Name }}{{ if .PersistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .PersistentVolumeClaim }}{{ end }}{{ if .SecretName }}
          secret:
            secretName: {{ .SecretName }}{{ end }}{{ if .ConfigMapName }}
          configMap:
            name: {{ .ConfigMapName }}{{ end }}{{ end }}
{{- end }}
`

const serviceTemplate = `apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Name }}
  ports:{{ range .Ports }}
    - name: {{ .Name }}
      protocol: {{ .Protocol }}
      port: {{ .Number }}
      targetPort: {{ .Number }}{{ end }}
`

const namespaceTemplate = `apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Namespace }}
`

const udsPackageTemplate = `apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: {{ .Name }}
spec:
  network:
    expose:
      - service: {{ .Name }}
        podLabels:
          app.kubernetes.io/name: {{ .Name }}
        gateway: tenant
        host: {{ .Host }}
        port: {{ .PrimaryPort }}
    allow:
      - direction: Ingress
        remoteGenerated: Anywhere
      - direction: Egress
        remoteGenerated: Anywhere
`
